export const customDinnerIdeas = [
  { id: "custom-1", name: "Honey garlic chicken thighs", protein: "chicken",
    ingredients: [{ name: "Chicken thighs", amount: "600", unit: "g" }, { name: "Honey", amount: "2", unit: "tbsp" }, { name: "Garlic", amount: "3", unit: "whole" }, { name: "Soy sauce", amount: "2", unit: "tbsp" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Salt", "Black pepper", "Ground ginger"], method: "oven", temp: "200C", time: "35 min", portions: 4,
    steps: "Marinate the chicken thighs for 20 min.\nBake at 200C, basting halfway through.\nServe over the rice." },
  { id: "custom-2", name: "Beef and ale stew", protein: "beef",
    ingredients: [{ name: "Diced beef", amount: "800", unit: "g" }, { name: "Ale", amount: "500", unit: "ml" }, { name: "Carrots", amount: "3", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "400", unit: "ml" }, { name: "Potatoes", amount: "4", unit: "whole" }],
    spices: ["Bay leaf", "Thyme", "Salt", "Black pepper"], method: "slow-cooker", temp: "Low", time: "2 hr", portions: 4,
    steps: "Brown the beef, then transfer to a slow cooker.\nAdd the ale, stock, carrots, onion, and potatoes.\nCook on low for 6-8 hours." },
  { id: "custom-3", name: "Chickpea and spinach curry", protein: "other",
    ingredients: [{ name: "Chickpeas", amount: "2", unit: "cup" }, { name: "Spinach", amount: "200", unit: "g" }, { name: "Coconut milk", amount: "400", unit: "ml" }, { name: "Curry paste", amount: "2", unit: "tbsp" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Cumin", "Turmeric", "Salt"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Fry onion until soft.\nAdd curry paste, chickpeas, spinach and coconut milk, simmer 15 min.\nServe over rice." },
  { id: "custom-4", name: "Lemon garlic salmon traybake", protein: "fish",
    ingredients: [{ name: "Salmon fillets", amount: "4", unit: "whole" }, { name: "New potatoes", amount: "600", unit: "g" }, { name: "Cherry tomatoes", amount: "200", unit: "g" }, { name: "Lemon", amount: "1", unit: "whole" }, { name: "Olive oil", amount: "2", unit: "tbsp" }],
    spices: ["Salt", "Black pepper", "Dried oregano"], method: "oven", temp: "200C", time: "30 min", portions: 4,
    steps: "Toss potatoes in oil, roast 15 min.\nAdd salmon and tomatoes, roast 15 min more.\nSqueeze lemon over before serving." },
  { id: "custom-5", name: "Beef and broccoli stir fry", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "500", unit: "g" }, { name: "Broccoli", amount: "300", unit: "g" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }, { name: "Garlic", amount: "3", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Cornflour", amount: "1", unit: "tbsp" }],
    spices: ["Ground ginger", "Black pepper"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry beef in hot oil until browned.\nAdd broccoli and garlic, cook 5 min.\nStir in soy sauce and cornflour slurry to thicken.\nServe over rice." },
  { id: "custom-6", name: "Sticky BBQ pork ribs", protein: "pork",
    ingredients: [{ name: "Pork ribs", amount: "1", unit: "kg" }, { name: "BBQ sauce", amount: "150", unit: "ml" }, { name: "Honey", amount: "2", unit: "tbsp" }, { name: "Coleslaw mix", amount: "300", unit: "g" }],
    spices: ["Smoked paprika", "Salt", "Garlic powder"], method: "bbq", temp: "180C", time: "45 min", portions: 4,
    steps: "Rub ribs with spices, wrap in foil.\nCook low and slow until tender.\nUnwrap, baste with BBQ sauce and honey, char for 5-10 min.\nServe with coleslaw." },
  { id: "custom-7", name: "Creamy mushroom chicken", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "600", unit: "g" }, { name: "Mushrooms", amount: "250", unit: "g" }, { name: "Double cream", amount: "200", unit: "ml" }, { name: "Chicken stock", amount: "150", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Tagliatelle", amount: "300", unit: "g" }],
    spices: ["Thyme", "Salt", "Black pepper"], method: "hob", temp: "", time: "30 min", portions: 4,
    steps: "Sear chicken, set aside.\nFry onion and mushrooms, add stock and cream.\nReturn chicken, simmer until cooked through.\nServe over tagliatelle." },
  { id: "custom-8", name: "Halloumi and veg air fryer skewers", protein: "other",
    ingredients: [{ name: "Halloumi", amount: "250", unit: "g" }, { name: "Peppers", amount: "2", unit: "whole" }, { name: "Courgette", amount: "1", unit: "whole" }, { name: "Red onion", amount: "1", unit: "whole" }, { name: "Olive oil", amount: "1", unit: "tbsp" }, { name: "Couscous", amount: "200", unit: "g" }],
    spices: ["Paprika", "Cumin", "Salt"], method: "airfryer", temp: "200C", time: "15 min", portions: 3,
    steps: "Cube halloumi and veg, thread onto skewers.\nAir fry 12-15 min, turning halfway.\nServe with couscous." },
  { id: "custom-9", name: "Slow cooker beef brisket", protein: "beef",
    ingredients: [{ name: "Beef brisket", amount: "1", unit: "kg" }, { name: "Beef stock", amount: "400", unit: "ml" }, { name: "Carrots", amount: "4", unit: "whole" }, { name: "Onion", amount: "2", unit: "whole" }, { name: "Worcestershire sauce", amount: "2", unit: "tbsp" }],
    spices: ["Bay leaf", "Black pepper", "Salt"], method: "slow-cooker", temp: "Low", time: "7 hr", portions: 6,
    steps: "Sear brisket, place in slow cooker with veg and stock.\nCook on low 7-8 hours.\nShred and serve with the cooking juices." },
  { id: "custom-10", name: "Prawn and chorizo pasta", protein: "fish",
    ingredients: [{ name: "Prawns", amount: "300", unit: "g" }, { name: "Chorizo", amount: "150", unit: "g" }, { name: "Cherry tomatoes", amount: "200", unit: "g" }, { name: "Garlic", amount: "2", unit: "whole" }, { name: "Spaghetti", amount: "300", unit: "g" }],
    spices: ["Chilli flakes", "Black pepper"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry chorizo until oil releases.\nAdd garlic and tomatoes, simmer 5 min.\nAdd prawns, cook until pink.\nToss through cooked spaghetti." },
  { id: "custom-11", name: "Vegetable chilli", protein: "other",
    ingredients: [{ name: "Kidney beans", amount: "2", unit: "cup" }, { name: "Black beans", amount: "1", unit: "cup" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Sweet potato", amount: "1", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "250", unit: "g" }],
    spices: ["Cumin", "Smoked paprika", "Chilli powder", "Salt"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Fry onion and sweet potato until softening.\nAdd beans, tomatoes and spices, simmer 25 min.\nServe over rice." },
  { id: "custom-12", name: "Grilled lamb chops with mint", protein: "other",
    ingredients: [{ name: "Lamb chops", amount: "8", unit: "whole" }, { name: "Mint", amount: "1", unit: "whole" }, { name: "New potatoes", amount: "500", unit: "g" }, { name: "Peas", amount: "200", unit: "g" }, { name: "Olive oil", amount: "1", unit: "tbsp" }],
    spices: ["Rosemary", "Garlic powder", "Salt", "Black pepper"], method: "grill", temp: "", time: "20 min", portions: 4,
    steps: "Season lamb, grill 4-5 min each side.\nBoil potatoes and peas.\nRest lamb 5 min, serve with mint." },
  { id: "custom-13", name: "Turkey meatballs in tomato sauce", protein: "chicken",
    ingredients: [{ name: "Turkey mince", amount: "500", unit: "g" }, { name: "Breadcrumbs", amount: "50", unit: "g" }, { name: "Egg", amount: "1", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Garlic", amount: "2", unit: "whole" }, { name: "Spaghetti", amount: "300", unit: "g" }],
    spices: ["Dried basil", "Oregano", "Salt", "Black pepper"], method: "oven", temp: "190C", time: "30 min", portions: 4,
    steps: "Mix mince, breadcrumbs, egg and seasoning, roll into balls.\nBake 15 min.\nSimmer in tomato sauce with garlic 10 min.\nServe over spaghetti." },
  { id: "custom-14", name: "Fish and chips (oven-baked)", protein: "fish",
    ingredients: [{ name: "Cod fillets", amount: "4", unit: "whole" }, { name: "Potatoes", amount: "800", unit: "g" }, { name: "Breadcrumbs", amount: "80", unit: "g" }, { name: "Egg", amount: "1", unit: "whole" }, { name: "Peas", amount: "200", unit: "g" }],
    spices: ["Salt", "Black pepper", "Paprika"], method: "oven", temp: "220C", time: "35 min", portions: 4,
    steps: "Cut potatoes into chips, toss in oil, roast 25 min.\nCoat cod in egg then breadcrumbs, bake alongside for last 15 min.\nBoil peas, serve together." },
  { id: "custom-15", name: "Microwave jacket potato with tuna mayo", protein: "fish",
    ingredients: [{ name: "Baking potatoes", amount: "4", unit: "whole" }, { name: "Tinned tuna", amount: "2", unit: "whole" }, { name: "Mayonnaise", amount: "3", unit: "tbsp" }, { name: "Sweetcorn", amount: "100", unit: "g" }, { name: "Cheddar", amount: "100", unit: "g" }],
    spices: ["Black pepper", "Salt"], method: "microwave", temp: "", time: "15 min", portions: 4,
    steps: "Pierce potatoes, microwave 8-10 min each, turning halfway.\nMix tuna, mayo and sweetcorn.\nSplit potatoes, top with tuna mix and cheese." },
  { id: "custom-16", name: "Chicken tikka masala", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "600", unit: "g" }, { name: "Yoghurt", amount: "150", unit: "ml" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Double cream", amount: "100", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Garlic", amount: "3", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Garam masala", "Turmeric", "Cumin", "Chilli powder"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Marinate chicken in yoghurt and spices 30 min.\nFry onion and garlic, add tomatoes, simmer 15 min.\nAdd chicken, cook through, stir in cream.\nServe over rice." },
  { id: "custom-17", name: "Beef lasagne", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Lasagne sheets", amount: "250", unit: "g" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Milk", amount: "500", unit: "ml" }, { name: "Plain flour", amount: "50", unit: "g" }, { name: "Butter", amount: "50", unit: "g" }, { name: "Cheddar", amount: "150", unit: "g" }],
    spices: ["Oregano", "Basil", "Salt", "Black pepper"], method: "oven", temp: "180C", time: "50 min", portions: 6,
    steps: "Brown mince with onion, add tomatoes, simmer 15 min.\nMake white sauce with butter, flour and milk.\nLayer mince, sheets and white sauce, top with cheese.\nBake 35-40 min." },
  { id: "custom-18", name: "Pork and apple sausages with mash", protein: "pork",
    ingredients: [{ name: "Pork sausages", amount: "8", unit: "whole" }, { name: "Potatoes", amount: "800", unit: "g" }, { name: "Apples", amount: "2", unit: "whole" }, { name: "Butter", amount: "50", unit: "g" }, { name: "Milk", amount: "100", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }],
    spices: ["Sage", "Black pepper", "Salt"], method: "oven", temp: "200C", time: "35 min", portions: 4,
    steps: "Roast sausages with sliced apple and onion.\nBoil and mash potatoes with butter and milk.\nServe sausages and apples over mash." },
  { id: "custom-19", name: "Cod in parsley sauce", protein: "fish",
    ingredients: [{ name: "Cod fillets", amount: "4", unit: "whole" }, { name: "Milk", amount: "300", unit: "ml" }, { name: "Butter", amount: "30", unit: "g" }, { name: "Plain flour", amount: "30", unit: "g" }, { name: "Parsley", amount: "1", unit: "whole" }, { name: "New potatoes", amount: "600", unit: "g" }],
    spices: ["Salt", "Black pepper"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Poach cod gently in milk 10 min, remove and keep warm.\nUse the milk to make a roux-based white sauce, stir in parsley.\nBoil potatoes, serve with cod and sauce." },
  { id: "custom-20", name: "Vegetable stir fry with tofu", protein: "other",
    ingredients: [{ name: "Firm tofu", amount: "400", unit: "g" }, { name: "Broccoli", amount: "200", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Sesame oil", amount: "1", unit: "tbsp" }],
    spices: ["Ground ginger", "Garlic powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry cubed tofu until golden, set aside.\nStir fry vegetables until tender-crisp.\nReturn tofu, add soy sauce and sesame oil.\nServe over rice." },
  { id: "custom-21", name: "Slow cooker chicken curry", protein: "chicken",
    ingredients: [{ name: "Chicken thighs", amount: "700", unit: "g" }, { name: "Coconut milk", amount: "400", unit: "ml" }, { name: "Curry paste", amount: "3", unit: "tbsp" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Potatoes", amount: "3", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Turmeric", "Cumin", "Salt"], method: "slow-cooker", temp: "Low", time: "5 hr", portions: 4,
    steps: "Add all ingredients except rice to the slow cooker.\nCook on low 5-6 hours.\nServe over rice." },
  { id: "custom-22", name: "Beef burgers with sweet potato fries", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Burger buns", amount: "4", unit: "whole" }, { name: "Sweet potatoes", amount: "600", unit: "g" }, { name: "Cheddar", amount: "4", unit: "whole" }, { name: "Lettuce", amount: "1", unit: "whole" }, { name: "Tomato", amount: "1", unit: "whole" }],
    spices: ["Garlic powder", "Smoked paprika", "Salt", "Black pepper"], method: "oven", temp: "220C", time: "30 min", portions: 4,
    steps: "Cut sweet potatoes into fries, toss in oil, roast 25 min.\nShape and grill/fry burgers 4-5 min each side, top with cheese.\nAssemble in buns with lettuce and tomato." },
  { id: "custom-23", name: "Pork stir fry noodles", protein: "pork",
    ingredients: [{ name: "Pork strips", amount: "500", unit: "g" }, { name: "Egg noodles", amount: "250", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Spring onion", amount: "1", unit: "whole" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }, { name: "Garlic", amount: "2", unit: "whole" }],
    spices: ["Ground ginger", "Chilli flakes"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry pork strips until browned.\nAdd peppers and garlic, cook 3-4 min.\nToss through cooked noodles, soy sauce and spring onion." },
  { id: "custom-24", name: "Baked stuffed peppers", protein: "other",
    ingredients: [{ name: "Peppers", amount: "4", unit: "whole" }, { name: "Rice", amount: "200", unit: "g" }, { name: "Black beans", amount: "1", unit: "cup" }, { name: "Sweetcorn", amount: "100", unit: "g" }, { name: "Cheddar", amount: "100", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }],
    spices: ["Cumin", "Paprika", "Salt"], method: "oven", temp: "190C", time: "35 min", portions: 4,
    steps: "Halve peppers, remove seeds.\nMix cooked rice, beans, sweetcorn and onion, fill peppers.\nTop with cheese, bake 30 min." },
  { id: "custom-25", name: "Chicken fajitas", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Peppers", amount: "2", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Tortilla wraps", amount: "8", unit: "whole" }, { name: "Soured cream", amount: "100", unit: "ml" }],
    spices: ["Paprika", "Cumin", "Chilli powder", "Garlic powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Slice chicken and vegetables into strips.\nFry with spices until chicken is cooked through.\nServe with warm tortillas and soured cream." },
  { id: "custom-26", name: "Roast beef Sunday dinner", protein: "beef",
    ingredients: [{ name: "Beef joint", amount: "1.2", unit: "kg" }, { name: "Potatoes", amount: "800", unit: "g" }, { name: "Carrots", amount: "4", unit: "whole" }, { name: "Yorkshire pudding batter", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "300", unit: "ml" }],
    spices: ["Rosemary", "Salt", "Black pepper"], method: "oven", temp: "180C", time: "90 min", portions: 6,
    steps: "Roast beef joint, resting time included, to preference.\nParboil and roast potatoes alongside.\nBoil carrots, make gravy from the stock and resting juices." },
  { id: "custom-27", name: "Fish tacos", protein: "fish",
    ingredients: [{ name: "White fish fillets", amount: "500", unit: "g" }, { name: "Small tortillas", amount: "8", unit: "whole" }, { name: "Cabbage", amount: "200", unit: "g" }, { name: "Lime", amount: "1", unit: "whole" }, { name: "Soured cream", amount: "100", unit: "ml" }],
    spices: ["Paprika", "Cumin", "Chilli powder"], method: "grill", temp: "", time: "20 min", portions: 4,
    steps: "Season and grill fish until flaky.\nShred cabbage, dress with lime.\nFlake fish into tortillas, top with cabbage and soured cream." },
  { id: "custom-28", name: "Vegetable lasagne", protein: "other",
    ingredients: [{ name: "Lasagne sheets", amount: "250", unit: "g" }, { name: "Courgette", amount: "1", unit: "whole" }, { name: "Aubergine", amount: "1", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Milk", amount: "500", unit: "ml" }, { name: "Plain flour", amount: "50", unit: "g" }, { name: "Butter", amount: "50", unit: "g" }, { name: "Cheddar", amount: "150", unit: "g" }],
    spices: ["Oregano", "Basil", "Salt"], method: "oven", temp: "180C", time: "50 min", portions: 6,
    steps: "Roast sliced courgette and aubergine 15 min.\nMake tomato sauce and white sauce separately.\nLayer vegetables, sheets, sauces; top with cheese.\nBake 35-40 min." },
  { id: "custom-29", name: "Slow cooker pulled pork", protein: "pork",
    ingredients: [{ name: "Pork shoulder", amount: "1.2", unit: "kg" }, { name: "BBQ sauce", amount: "200", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Brioche buns", amount: "6", unit: "whole" }, { name: "Coleslaw mix", amount: "300", unit: "g" }],
    spices: ["Smoked paprika", "Garlic powder", "Salt"], method: "slow-cooker", temp: "Low", time: "8 hr", portions: 6,
    steps: "Rub pork with spices, place in slow cooker with onion.\nCook on low 8 hours until falling apart.\nShred, mix through BBQ sauce, serve in buns with coleslaw." },
  { id: "custom-30", name: "Chicken Caesar salad", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "400", unit: "g" }, { name: "Romaine lettuce", amount: "1", unit: "whole" }, { name: "Parmesan", amount: "50", unit: "g" }, { name: "Croutons", amount: "80", unit: "g" }, { name: "Caesar dressing", amount: "80", unit: "ml" }],
    spices: ["Black pepper", "Garlic powder"], method: "grill", temp: "", time: "20 min", portions: 2,
    steps: "Grill or pan-fry chicken until cooked, slice.\nToss lettuce with dressing.\nTop with chicken, parmesan and croutons." },
  { id: "custom-31", name: "Beef chow mein", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "500", unit: "g" }, { name: "Egg noodles", amount: "250", unit: "g" }, { name: "Beansprouts", amount: "150", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }],
    spices: ["Ground ginger", "Chinese five spice"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry beef until browned, set aside.\nStir fry vegetables 3-4 min.\nAdd noodles, beef and soy sauce, toss together." },
  { id: "custom-32", name: "Baked chicken parmesan", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "4", unit: "whole" }, { name: "Breadcrumbs", amount: "100", unit: "g" }, { name: "Egg", amount: "2", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Mozzarella", amount: "150", unit: "g" }, { name: "Spaghetti", amount: "300", unit: "g" }],
    spices: ["Basil", "Oregano", "Salt"], method: "oven", temp: "200C", time: "35 min", portions: 4,
    steps: "Coat chicken in egg then breadcrumbs, bake 20 min.\nTop with tomato sauce and mozzarella, bake 10 min more.\nServe with spaghetti." },
  { id: "custom-33", name: "Sausage and lentil casserole", protein: "pork",
    ingredients: [{ name: "Pork sausages", amount: "6", unit: "whole" }, { name: "Red lentils", amount: "200", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Vegetable stock", amount: "600", unit: "ml" }],
    spices: ["Thyme", "Bay leaf", "Salt"], method: "oven", temp: "180C", time: "45 min", portions: 4,
    steps: "Brown sausages, set aside.\nSauté onion and carrots, add lentils and stock.\nReturn sausages, cover and bake 35 min." },
  { id: "custom-34", name: "Salmon teriyaki", protein: "fish",
    ingredients: [{ name: "Salmon fillets", amount: "4", unit: "whole" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }, { name: "Honey", amount: "2", unit: "tbsp" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Broccoli", amount: "200", unit: "g" }],
    spices: ["Ground ginger", "Garlic powder"], method: "grill", temp: "", time: "20 min", portions: 4,
    steps: "Mix soy sauce and honey, marinate salmon 15 min.\nGrill salmon until just cooked through.\nSteam broccoli, serve with rice." },
  { id: "custom-35", name: "Vegetable and bean burritos", protein: "other",
    ingredients: [{ name: "Black beans", amount: "2", unit: "cup" }, { name: "Rice", amount: "200", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Tortilla wraps", amount: "6", unit: "whole" }, { name: "Cheddar", amount: "100", unit: "g" }],
    spices: ["Cumin", "Paprika", "Chilli powder"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Fry onion and peppers, add beans and spices.\nWarm rice and wraps.\nAssemble burritos with beans, rice and cheese." },
  { id: "custom-36", name: "Chicken and chorizo paella", protein: "chicken",
    ingredients: [{ name: "Chicken thighs", amount: "500", unit: "g" }, { name: "Chorizo", amount: "150", unit: "g" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Chicken stock", amount: "600", unit: "ml" }, { name: "Peas", amount: "100", unit: "g" }],
    spices: ["Smoked paprika", "Turmeric", "Salt"], method: "hob", temp: "", time: "40 min", portions: 4,
    steps: "Brown chicken and chorizo, set aside.\nFry peppers, add rice and stock, simmer.\nReturn chicken and chorizo, stir in peas near the end." },
  { id: "custom-37", name: "Beef and Guinness pie", protein: "beef",
    ingredients: [{ name: "Diced beef", amount: "700", unit: "g" }, { name: "Guinness", amount: "330", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Puff pastry", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "300", unit: "ml" }],
    spices: ["Thyme", "Bay leaf", "Black pepper"], method: "oven", temp: "190C", time: "2 hr", portions: 6,
    steps: "Brown beef, add onion, carrots, Guinness and stock.\nSimmer or braise 1.5 hours until tender.\nTop with pastry, bake 25-30 min until golden." },
  { id: "custom-38", name: "Pork chops with apple sauce", protein: "pork",
    ingredients: [{ name: "Pork chops", amount: "4", unit: "whole" }, { name: "Apples", amount: "2", unit: "whole" }, { name: "Potatoes", amount: "600", unit: "g" }, { name: "Green beans", amount: "200", unit: "g" }, { name: "Butter", amount: "20", unit: "g" }],
    spices: ["Sage", "Salt", "Black pepper"], method: "grill", temp: "", time: "25 min", portions: 4,
    steps: "Grill pork chops until cooked through.\nSimmer diced apples with a little water until soft, mash.\nBoil potatoes and beans, serve alongside." },
  { id: "custom-39", name: "Thai green curry", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Coconut milk", amount: "400", unit: "ml" }, { name: "Green curry paste", amount: "3", unit: "tbsp" }, { name: "Green beans", amount: "150", unit: "g" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Fish sauce", "Basil"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Fry curry paste for a minute, add chicken to seal.\nAdd coconut milk and green beans, simmer 15 min.\nServe over rice." },
  { id: "custom-40", name: "Vegetable and chickpea tagine", protein: "other",
    ingredients: [{ name: "Chickpeas", amount: "2", unit: "cup" }, { name: "Sweet potato", amount: "1", unit: "whole" }, { name: "Courgette", amount: "1", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Couscous", amount: "200", unit: "g" }],
    spices: ["Cumin", "Cinnamon", "Coriander"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Fry onion, add spices, sweet potato and tomatoes.\nSimmer 20 min, add chickpeas and courgette, cook 10 min more.\nServe with couscous." },
  { id: "custom-41", name: "Beef tacos", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Taco shells", amount: "8", unit: "whole" }, { name: "Cheddar", amount: "100", unit: "g" }, { name: "Lettuce", amount: "1", unit: "whole" }, { name: "Tomato", amount: "1", unit: "whole" }, { name: "Soured cream", amount: "100", unit: "ml" }],
    spices: ["Cumin", "Paprika", "Chilli powder", "Garlic powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Brown mince with spices.\nWarm taco shells.\nFill with mince, cheese, lettuce, tomato and soured cream." },
  { id: "custom-42", name: "Chicken noodle soup", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "400", unit: "g" }, { name: "Egg noodles", amount: "150", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Celery", amount: "2", unit: "whole" }, { name: "Chicken stock", amount: "1", unit: "l" }],
    spices: ["Thyme", "Salt", "Black pepper"], method: "hob", temp: "", time: "30 min", portions: 4,
    steps: "Simmer chicken in stock with carrots and celery until cooked.\nShred chicken, return to pot.\nAdd noodles, cook until tender." },
  { id: "custom-43", name: "Air fryer chicken wings", protein: "chicken",
    ingredients: [{ name: "Chicken wings", amount: "1", unit: "kg" }, { name: "Hot sauce", amount: "60", unit: "ml" }, { name: "Butter", amount: "30", unit: "g" }, { name: "Celery", amount: "2", unit: "whole" }],
    spices: ["Garlic powder", "Paprika", "Salt"], method: "airfryer", temp: "200C", time: "25 min", portions: 4,
    steps: "Toss wings in spices, air fry 20-25 min, shaking halfway.\nMelt butter with hot sauce, toss wings through.\nServe with celery sticks." },
  { id: "custom-44", name: "Beef stroganoff", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "500", unit: "g" }, { name: "Mushrooms", amount: "250", unit: "g" }, { name: "Soured cream", amount: "200", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "150", unit: "ml" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Paprika", "Black pepper"], method: "hob", temp: "", time: "30 min", portions: 4,
    steps: "Brown beef, set aside.\nFry onion and mushrooms, add stock and paprika.\nReturn beef, stir in soured cream, serve over rice." },
  { id: "custom-45", name: "Vegetable fried rice", protein: "other",
    ingredients: [{ name: "Rice", amount: "300", unit: "g" }, { name: "Peas", amount: "100", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Egg", amount: "2", unit: "whole" }, { name: "Soy sauce", amount: "2", unit: "tbsp" }, { name: "Spring onion", amount: "1", unit: "whole" }],
    spices: ["Ground ginger", "Garlic powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Scramble eggs, set aside.\nFry carrots and peas, add cooked rice.\nStir through soy sauce, egg and spring onion." },
  { id: "custom-46", name: "Pork and pineapple skewers", protein: "pork",
    ingredients: [{ name: "Pork loin", amount: "500", unit: "g" }, { name: "Pineapple", amount: "1", unit: "whole" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Soy sauce", amount: "2", unit: "tbsp" }],
    spices: ["Ground ginger", "Garlic powder"], method: "bbq", temp: "", time: "20 min", portions: 4,
    steps: "Cube pork, pineapple and peppers, thread onto skewers.\nBrush with soy sauce, grill/BBQ 15-18 min turning occasionally.\nServe with rice." },
  { id: "custom-47", name: "Chicken katsu curry", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "4", unit: "whole" }, { name: "Breadcrumbs", amount: "100", unit: "g" }, { name: "Egg", amount: "1", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Curry powder", amount: "2", unit: "tbsp" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Turmeric", "Garlic powder"], method: "oven", temp: "200C", time: "35 min", portions: 4,
    steps: "Coat chicken in egg then breadcrumbs, bake 20-25 min.\nFry onion, add curry powder and a little stock, simmer to a sauce.\nSlice chicken, serve over rice with sauce." },
  { id: "custom-48", name: "Beef and vegetable skewers", protein: "beef",
    ingredients: [{ name: "Beef chunks", amount: "500", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Red onion", amount: "1", unit: "whole" }, { name: "Courgette", amount: "1", unit: "whole" }, { name: "Couscous", amount: "200", unit: "g" }],
    spices: ["Smoked paprika", "Cumin", "Salt"], method: "grill", temp: "", time: "20 min", portions: 4,
    steps: "Thread beef and vegetables onto skewers.\nSeason and grill 12-15 min, turning occasionally.\nServe with couscous." },
  { id: "custom-49", name: "Sausage casserole", protein: "pork",
    ingredients: [{ name: "Pork sausages", amount: "6", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Butter beans", amount: "1", unit: "cup" }],
    spices: ["Thyme", "Bay leaf", "Salt"], method: "oven", temp: "180C", time: "50 min", portions: 4,
    steps: "Brown sausages, set aside.\nFry onion and carrots, add tomatoes and beans.\nReturn sausages, cover and bake 40 min." },
  { id: "custom-50", name: "Cajun salmon with rice", protein: "fish",
    ingredients: [{ name: "Salmon fillets", amount: "4", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Sweetcorn", amount: "100", unit: "g" }, { name: "Lime", amount: "1", unit: "whole" }],
    spices: ["Cajun seasoning", "Salt"], method: "oven", temp: "200C", time: "25 min", portions: 4,
    steps: "Season salmon with Cajun spice, bake 15-18 min.\nCook rice with peppers and sweetcorn stirred through.\nSqueeze lime over before serving." },
  { id: "custom-51", name: "Vegetable moussaka", protein: "other",
    ingredients: [{ name: "Aubergine", amount: "2", unit: "whole" }, { name: "Lentils", amount: "1", unit: "cup" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Milk", amount: "400", unit: "ml" }, { name: "Plain flour", amount: "40", unit: "g" }, { name: "Butter", amount: "40", unit: "g" }, { name: "Cheddar", amount: "100", unit: "g" }],
    spices: ["Cinnamon", "Oregano", "Salt"], method: "oven", temp: "190C", time: "50 min", portions: 4,
    steps: "Roast sliced aubergine 15 min.\nSimmer lentils with tomatoes and cinnamon.\nLayer aubergine and lentil mix, top with white sauce and cheese, bake 30 min." },
  { id: "custom-52", name: "Chicken shawarma wraps", protein: "chicken",
    ingredients: [{ name: "Chicken thighs", amount: "600", unit: "g" }, { name: "Yoghurt", amount: "100", unit: "ml" }, { name: "Tortilla wraps", amount: "6", unit: "whole" }, { name: "Cucumber", amount: "1", unit: "whole" }, { name: "Tomato", amount: "1", unit: "whole" }],
    spices: ["Cumin", "Paprika", "Garlic powder", "Turmeric"], method: "grill", temp: "", time: "25 min", portions: 4,
    steps: "Marinate chicken in yoghurt and spices 20 min.\nGrill until charred and cooked through, slice.\nServe in wraps with cucumber and tomato." },
  { id: "custom-53", name: "Beef and mushroom pie", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Mushrooms", amount: "200", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "300", unit: "ml" }, { name: "Puff pastry", amount: "1", unit: "whole" }],
    spices: ["Thyme", "Black pepper"], method: "oven", temp: "190C", time: "45 min", portions: 4,
    steps: "Brown mince and onion, add mushrooms and stock, simmer 15 min.\nTransfer to a dish, top with pastry.\nBake 25-30 min until golden." },
  { id: "custom-54", name: "Prawn stir fry with noodles", protein: "fish",
    ingredients: [{ name: "Prawns", amount: "400", unit: "g" }, { name: "Egg noodles", amount: "250", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Beansprouts", amount: "150", unit: "g" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }],
    spices: ["Ground ginger", "Chilli flakes"], method: "hob", temp: "", time: "18 min", portions: 4,
    steps: "Stir fry peppers, add prawns until pink.\nAdd noodles, beansprouts and soy sauce, toss together." },
  { id: "custom-55", name: "Vegetable and halloumi traybake", protein: "other",
    ingredients: [{ name: "Halloumi", amount: "250", unit: "g" }, { name: "Sweet potato", amount: "2", unit: "whole" }, { name: "Red onion", amount: "1", unit: "whole" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Olive oil", amount: "2", unit: "tbsp" }],
    spices: ["Smoked paprika", "Cumin", "Salt"], method: "oven", temp: "200C", time: "35 min", portions: 4,
    steps: "Toss vegetables in oil and spices, roast 20 min.\nAdd sliced halloumi, roast 15 min more." },
  { id: "custom-56", name: "Chicken and leek pie", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Leeks", amount: "2", unit: "whole" }, { name: "Double cream", amount: "200", unit: "ml" }, { name: "Chicken stock", amount: "200", unit: "ml" }, { name: "Puff pastry", amount: "1", unit: "whole" }],
    spices: ["Thyme", "Black pepper"], method: "oven", temp: "190C", time: "45 min", portions: 4,
    steps: "Poach chicken with leeks in stock until cooked, shred.\nStir in cream, transfer to a dish, top with pastry.\nBake 25-30 min until golden." },
  { id: "custom-57", name: "Beef bourguignon", protein: "beef",
    ingredients: [{ name: "Diced beef", amount: "800", unit: "g" }, { name: "Red wine", amount: "300", unit: "ml" }, { name: "Bacon lardons", amount: "100", unit: "g" }, { name: "Carrots", amount: "3", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "300", unit: "ml" }],
    spices: ["Thyme", "Bay leaf", "Black pepper"], method: "slow-cooker", temp: "Low", time: "5 hr", portions: 6,
    steps: "Brown beef and lardons, transfer to slow cooker.\nAdd wine, stock, carrots and onion.\nCook on low 5-6 hours until tender." },
  { id: "custom-58", name: "Vegetable pad thai", protein: "other",
    ingredients: [{ name: "Rice noodles", amount: "250", unit: "g" }, { name: "Egg", amount: "2", unit: "whole" }, { name: "Beansprouts", amount: "150", unit: "g" }, { name: "Peanuts", amount: "50", unit: "g" }, { name: "Lime", amount: "1", unit: "whole" }, { name: "Soy sauce", amount: "2", unit: "tbsp" }],
    spices: ["Chilli flakes"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Soak noodles until soft.\nScramble egg, add beansprouts and noodles, toss with soy sauce.\nTop with peanuts and a squeeze of lime." },
  { id: "custom-59", name: "Pork tenderloin with roasted veg", protein: "pork",
    ingredients: [{ name: "Pork tenderloin", amount: "600", unit: "g" }, { name: "Potatoes", amount: "500", unit: "g" }, { name: "Carrots", amount: "3", unit: "whole" }, { name: "Parsnips", amount: "2", unit: "whole" }, { name: "Olive oil", amount: "2", unit: "tbsp" }],
    spices: ["Rosemary", "Salt", "Black pepper"], method: "oven", temp: "200C", time: "40 min", portions: 4,
    steps: "Roast vegetables in oil for 15 min.\nSeason pork, add to the tray, roast 25 min more.\nRest pork 5 min before slicing." },
  { id: "custom-60", name: "Chicken quesadillas", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "400", unit: "g" }, { name: "Tortilla wraps", amount: "6", unit: "whole" }, { name: "Cheddar", amount: "150", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }],
    spices: ["Cumin", "Paprika", "Chilli powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Cook chicken, peppers and onion with spices.\nLayer between tortillas with cheese.\nToast in a dry pan until golden and cheese melts." },
  { id: "custom-61", name: "Baked cod with crushed potatoes", protein: "fish",
    ingredients: [{ name: "Cod fillets", amount: "4", unit: "whole" }, { name: "New potatoes", amount: "600", unit: "g" }, { name: "Peas", amount: "150", unit: "g" }, { name: "Butter", amount: "30", unit: "g" }, { name: "Lemon", amount: "1", unit: "whole" }],
    spices: ["Salt", "Black pepper", "Dill"], method: "oven", temp: "200C", time: "25 min", portions: 4,
    steps: "Bake cod 15-18 min until flaky.\nBoil and crush potatoes with butter.\nBoil peas, serve everything together with a squeeze of lemon." },
  { id: "custom-62", name: "Vegetable shepherd's pie", protein: "other",
    ingredients: [{ name: "Lentils", amount: "2", unit: "cup" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Vegetable stock", amount: "300", unit: "ml" }, { name: "Potatoes", amount: "800", unit: "g" }, { name: "Butter", amount: "40", unit: "g" }],
    spices: ["Thyme", "Worcestershire sauce", "Salt"], method: "oven", temp: "190C", time: "45 min", portions: 4,
    steps: "Simmer lentils, carrots and onion in stock until thick.\nTop with mashed potato.\nBake 25-30 min until golden on top." },
  { id: "custom-63", name: "Chicken and sweetcorn soup", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "300", unit: "g" }, { name: "Sweetcorn", amount: "300", unit: "g" }, { name: "Chicken stock", amount: "1", unit: "l" }, { name: "Egg", amount: "1", unit: "whole" }, { name: "Cornflour", amount: "1", unit: "tbsp" }],
    spices: ["Ground ginger", "Soy sauce"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Simmer chicken in stock until cooked, shred.\nAdd sweetcorn, thicken with cornflour slurry.\nDrizzle in beaten egg while stirring." },
  { id: "custom-64", name: "Beef and black bean stir fry", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "500", unit: "g" }, { name: "Black bean sauce", amount: "100", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Ground ginger", "Garlic powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry beef until browned, set aside.\nStir fry peppers and onion, add black bean sauce.\nReturn beef, toss together, serve over rice." },
  { id: "custom-65", name: "Spiced cauliflower and chickpea traybake", protein: "other",
    ingredients: [{ name: "Cauliflower", amount: "1", unit: "whole" }, { name: "Chickpeas", amount: "2", unit: "cup" }, { name: "Red onion", amount: "1", unit: "whole" }, { name: "Olive oil", amount: "2", unit: "tbsp" }, { name: "Couscous", amount: "200", unit: "g" }],
    spices: ["Cumin", "Turmeric", "Coriander", "Salt"], method: "oven", temp: "200C", time: "35 min", portions: 4,
    steps: "Toss cauliflower, chickpeas and onion in oil and spices.\nRoast 30-35 min until charred at edges.\nServe with couscous." },
  { id: "custom-66", name: "Pork and leek sausage rolls with salad", protein: "pork",
    ingredients: [{ name: "Pork sausages", amount: "6", unit: "whole" }, { name: "Leeks", amount: "1", unit: "whole" }, { name: "Puff pastry", amount: "1", unit: "whole" }, { name: "Mixed salad", amount: "200", unit: "g" }, { name: "Egg", amount: "1", unit: "whole" }],
    spices: ["Thyme", "Black pepper"], method: "oven", temp: "200C", time: "30 min", portions: 4,
    steps: "Mix sausage meat with sautéed leek.\nRoll in pastry, brush with egg, bake 25 min until golden.\nServe with salad." },
  { id: "custom-67", name: "Chicken and vegetable hotpot", protein: "chicken",
    ingredients: [{ name: "Chicken thighs", amount: "600", unit: "g" }, { name: "Potatoes", amount: "600", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Chicken stock", amount: "500", unit: "ml" }],
    spices: ["Thyme", "Bay leaf", "Salt"], method: "oven", temp: "180C", time: "70 min", portions: 4,
    steps: "Layer sliced potatoes over chicken, carrots and onion in a dish.\nPour over stock.\nCover and bake 50 min, uncover for last 20 min to crisp the top." },
  { id: "custom-68", name: "Beef and pepper fajita bowls", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "500", unit: "g" }, { name: "Peppers", amount: "2", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Soured cream", amount: "100", unit: "ml" }],
    spices: ["Cumin", "Paprika", "Chilli powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry beef with spices until browned.\nAdd peppers and onion, cook until softened.\nServe over rice with soured cream." },
  { id: "custom-69", name: "Vegetable and lentil bolognese", protein: "other",
    ingredients: [{ name: "Lentils", amount: "2", unit: "cup" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Spaghetti", amount: "300", unit: "g" }],
    spices: ["Oregano", "Basil", "Salt"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Fry onion and carrots until soft.\nAdd lentils and tomatoes, simmer 25 min.\nServe over spaghetti." },
  { id: "custom-70", name: "Chicken and bacon pasta bake", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "400", unit: "g" }, { name: "Bacon lardons", amount: "100", unit: "g" }, { name: "Pasta", amount: "300", unit: "g" }, { name: "Double cream", amount: "200", unit: "ml" }, { name: "Cheddar", amount: "100", unit: "g" }],
    spices: ["Black pepper", "Garlic powder"], method: "oven", temp: "190C", time: "35 min", portions: 4,
    steps: "Cook chicken and bacon until browned.\nMix with cooked pasta and cream, transfer to a dish.\nTop with cheese, bake 20 min until golden." },
  { id: "custom-71", name: "Beef and vegetable soup", protein: "beef",
    ingredients: [{ name: "Diced beef", amount: "400", unit: "g" }, { name: "Carrots", amount: "3", unit: "whole" }, { name: "Potatoes", amount: "2", unit: "whole" }, { name: "Beef stock", amount: "1", unit: "l" }, { name: "Onion", amount: "1", unit: "whole" }],
    spices: ["Thyme", "Bay leaf", "Salt"], method: "slow-cooker", temp: "Low", time: "6 hr", portions: 4,
    steps: "Add all ingredients to the slow cooker.\nCook on low 6 hours until beef is tender." },
  { id: "custom-72", name: "Air fryer salmon with asparagus", protein: "fish",
    ingredients: [{ name: "Salmon fillets", amount: "4", unit: "whole" }, { name: "Asparagus", amount: "200", unit: "g" }, { name: "Lemon", amount: "1", unit: "whole" }, { name: "New potatoes", amount: "500", unit: "g" }, { name: "Olive oil", amount: "1", unit: "tbsp" }],
    spices: ["Salt", "Black pepper"], method: "airfryer", temp: "200C", time: "18 min", portions: 4,
    steps: "Air fry salmon and asparagus 10-12 min.\nBoil potatoes, serve everything together with a squeeze of lemon." },
  { id: "custom-73", name: "Vegetable curry with paneer", protein: "other",
    ingredients: [{ name: "Paneer", amount: "250", unit: "g" }, { name: "Spinach", amount: "200", unit: "g" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Garam masala", "Turmeric", "Cumin"], method: "hob", temp: "", time: "30 min", portions: 4,
    steps: "Fry onion and spices, add tomatoes, simmer 10 min.\nAdd paneer and spinach, cook until wilted.\nServe over rice." },
  { id: "custom-74", name: "Chicken drumsticks with corn on the cob", protein: "chicken",
    ingredients: [{ name: "Chicken drumsticks", amount: "8", unit: "whole" }, { name: "Corn on the cob", amount: "4", unit: "whole" }, { name: "Potatoes", amount: "600", unit: "g" }, { name: "Butter", amount: "30", unit: "g" }],
    spices: ["Smoked paprika", "Garlic powder", "Salt"], method: "oven", temp: "200C", time: "40 min", portions: 4,
    steps: "Season drumsticks with spices, roast 35-40 min.\nBoil corn and potatoes, toss potatoes in butter.\nServe together." },
  { id: "custom-75", name: "Beef and spinach curry", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Spinach", amount: "200", unit: "g" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Garam masala", "Cumin", "Turmeric"], method: "hob", temp: "", time: "30 min", portions: 4,
    steps: "Brown mince with onion and spices.\nAdd tomatoes, simmer 15 min.\nStir in spinach until wilted, serve over rice." },
  { id: "custom-76", name: "Vegetable and feta filo pie", protein: "other",
    ingredients: [{ name: "Spinach", amount: "300", unit: "g" }, { name: "Feta", amount: "200", unit: "g" }, { name: "Filo pastry", amount: "6", unit: "whole" }, { name: "Egg", amount: "2", unit: "whole" }, { name: "Butter", amount: "30", unit: "g" }],
    spices: ["Nutmeg", "Black pepper"], method: "oven", temp: "190C", time: "35 min", portions: 4,
    steps: "Mix wilted spinach with feta and beaten egg.\nLayer buttered filo sheets in a dish, add filling, top with more filo.\nBake 30 min until golden." },
  { id: "custom-77", name: "Chicken and mushroom risotto", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "400", unit: "g" }, { name: "Risotto rice", amount: "300", unit: "g" }, { name: "Mushrooms", amount: "200", unit: "g" }, { name: "Chicken stock", amount: "800", unit: "ml" }, { name: "Parmesan", amount: "50", unit: "g" }],
    spices: ["Thyme", "Black pepper"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Fry chicken and mushrooms, set aside.\nToast rice, gradually add stock, stirring until absorbed.\nStir in chicken, mushrooms and parmesan to finish." },
  { id: "custom-78", name: "Beef meatball subs", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Breadcrumbs", amount: "50", unit: "g" }, { name: "Egg", amount: "1", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Sub rolls", amount: "4", unit: "whole" }, { name: "Mozzarella", amount: "100", unit: "g" }],
    spices: ["Oregano", "Basil", "Garlic powder", "Salt"], method: "oven", temp: "190C", time: "35 min", portions: 4,
    steps: "Mix mince, breadcrumbs and egg, roll into balls, bake 15 min.\nSimmer in tomato sauce 10 min.\nFill rolls with meatballs and sauce, top with mozzarella and melt under the grill." },
  { id: "custom-79", name: "Vegetable dahl", protein: "other",
    ingredients: [{ name: "Red lentils", amount: "250", unit: "g" }, { name: "Spinach", amount: "150", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Vegetable stock", amount: "600", unit: "ml" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Turmeric", "Cumin", "Coriander"], method: "hob", temp: "", time: "30 min", portions: 4,
    steps: "Fry onion and spices, add lentils and stock.\nSimmer 20 min until lentils break down.\nStir in spinach, serve with rice." },
  { id: "custom-80", name: "Chicken schnitzel with potato salad", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "4", unit: "whole" }, { name: "Breadcrumbs", amount: "100", unit: "g" }, { name: "Egg", amount: "1", unit: "whole" }, { name: "New potatoes", amount: "500", unit: "g" }, { name: "Mayonnaise", amount: "80", unit: "g" }],
    spices: ["Salt", "Black pepper", "Paprika"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Coat chicken in egg then breadcrumbs, fry until golden and cooked through.\nBoil potatoes, toss with mayonnaise once cooled slightly.\nServe together." },
  { id: "custom-81", name: "Beef and vegetable kebabs with flatbread", protein: "beef",
    ingredients: [{ name: "Beef chunks", amount: "500", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Red onion", amount: "1", unit: "whole" }, { name: "Flatbreads", amount: "4", unit: "whole" }, { name: "Yoghurt", amount: "100", unit: "ml" }],
    spices: ["Cumin", "Smoked paprika", "Salt"], method: "bbq", temp: "", time: "20 min", portions: 4,
    steps: "Thread beef and vegetables onto skewers, season.\nGrill/BBQ 12-15 min, turning occasionally.\nServe in warm flatbreads with yoghurt." },
  { id: "custom-82", name: "Vegetable and bean stew", protein: "other",
    ingredients: [{ name: "Butter beans", amount: "2", unit: "cup" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Celery", amount: "2", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Vegetable stock", amount: "400", unit: "ml" }],
    spices: ["Thyme", "Bay leaf", "Salt"], method: "slow-cooker", temp: "Low", time: "5 hr", portions: 4,
    steps: "Add all ingredients to the slow cooker.\nCook on low 5-6 hours until vegetables are tender." },
  { id: "custom-83", name: "Chicken tikka skewers", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "600", unit: "g" }, { name: "Yoghurt", amount: "100", unit: "ml" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Lemon", amount: "1", unit: "whole" }],
    spices: ["Garam masala", "Turmeric", "Chilli powder"], method: "grill", temp: "", time: "25 min", portions: 4,
    steps: "Marinate chicken in yoghurt and spices 20 min.\nThread with peppers onto skewers, grill 12-15 min.\nServe over rice with a squeeze of lemon." },
  { id: "custom-84", name: "Beef and onion gravy sausages", protein: "beef",
    ingredients: [{ name: "Beef sausages", amount: "6", unit: "whole" }, { name: "Onion", amount: "2", unit: "whole" }, { name: "Beef stock", amount: "300", unit: "ml" }, { name: "Potatoes", amount: "800", unit: "g" }, { name: "Butter", amount: "40", unit: "g" }],
    spices: ["Thyme", "Black pepper"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Brown sausages, set aside.\nCaramelise onions slowly, add stock to make gravy.\nMash potatoes with butter, serve with sausages and gravy." },
  { id: "custom-85", name: "Vegetable and mushroom stroganoff", protein: "other",
    ingredients: [{ name: "Mushrooms", amount: "400", unit: "g" }, { name: "Soured cream", amount: "200", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Vegetable stock", amount: "150", unit: "ml" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Paprika", "Black pepper"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Fry onion and mushrooms until softened.\nAdd stock and paprika, simmer 5 min.\nStir in soured cream, serve over rice." },
  { id: "custom-86", name: "Chicken burrito bowls", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Black beans", amount: "1", unit: "cup" }, { name: "Sweetcorn", amount: "100", unit: "g" }, { name: "Soured cream", amount: "100", unit: "ml" }],
    spices: ["Cumin", "Paprika", "Chilli powder"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Season and cook chicken, slice.\nWarm beans and sweetcorn.\nBuild bowls with rice, beans, sweetcorn, chicken and soured cream." },
  { id: "custom-87", name: "Beef and red wine casserole", protein: "beef",
    ingredients: [{ name: "Diced beef", amount: "800", unit: "g" }, { name: "Red wine", amount: "250", unit: "ml" }, { name: "Carrots", amount: "3", unit: "whole" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Beef stock", amount: "300", unit: "ml" }],
    spices: ["Thyme", "Bay leaf", "Black pepper"], method: "oven", temp: "160C", time: "2 hr", portions: 6,
    steps: "Brown beef, transfer to a casserole dish with vegetables, wine and stock.\nCover and cook low and slow in the oven 2 hours until tender." },
  { id: "custom-88", name: "Vegetable and egg fried rice bowls", protein: "other",
    ingredients: [{ name: "Rice", amount: "300", unit: "g" }, { name: "Egg", amount: "3", unit: "whole" }, { name: "Peas", amount: "100", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Soy sauce", amount: "2", unit: "tbsp" }],
    spices: ["Ground ginger"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Scramble eggs, set aside.\nFry carrots and peas, add cooked rice and soy sauce.\nStir through egg to finish." },
  { id: "custom-89", name: "Chicken and vegetable pot pie", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Mixed vegetables", amount: "300", unit: "g" }, { name: "Chicken stock", amount: "300", unit: "ml" }, { name: "Double cream", amount: "100", unit: "ml" }, { name: "Puff pastry", amount: "1", unit: "whole" }],
    spices: ["Thyme", "Black pepper"], method: "oven", temp: "190C", time: "45 min", portions: 4,
    steps: "Poach chicken and vegetables in stock until cooked.\nStir in cream, transfer to a dish, top with pastry.\nBake 25-30 min until golden." },
  { id: "custom-90", name: "Beef and vegetable noodle soup", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "300", unit: "g" }, { name: "Egg noodles", amount: "200", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Beef stock", amount: "1", unit: "l" }, { name: "Spring onion", amount: "1", unit: "whole" }],
    spices: ["Ground ginger", "Soy sauce"], method: "hob", temp: "", time: "25 min", portions: 4,
    steps: "Simmer beef and carrots in stock until tender.\nAdd noodles, cook until soft.\nGarnish with spring onion." },
  { id: "custom-91", name: "Vegetable quiche with side salad", protein: "other",
    ingredients: [{ name: "Eggs", amount: "4", unit: "whole" }, { name: "Milk", amount: "150", unit: "ml" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Cheddar", amount: "100", unit: "g" }, { name: "Shortcrust pastry", amount: "1", unit: "whole" }, { name: "Mixed salad", amount: "200", unit: "g" }],
    spices: ["Black pepper", "Salt"], method: "oven", temp: "180C", time: "40 min", portions: 4,
    steps: "Line a tin with pastry, blind bake 10 min.\nMix eggs, milk, peppers and cheese, pour into the case.\nBake 25-30 min until set. Serve with salad." },
  { id: "custom-92", name: "Chicken and vegetable stir fry noodles", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Egg noodles", amount: "250", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Beansprouts", amount: "150", unit: "g" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }],
    spices: ["Ground ginger", "Garlic powder"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry chicken until cooked through, set aside.\nStir fry peppers and beansprouts.\nAdd noodles, chicken and soy sauce, toss together." },
  { id: "custom-93", name: "Beef koftas with flatbread", protein: "beef",
    ingredients: [{ name: "Beef mince", amount: "500", unit: "g" }, { name: "Flatbreads", amount: "4", unit: "whole" }, { name: "Cucumber", amount: "1", unit: "whole" }, { name: "Yoghurt", amount: "100", unit: "ml" }, { name: "Mint", amount: "1", unit: "whole" }],
    spices: ["Cumin", "Coriander", "Smoked paprika"], method: "grill", temp: "", time: "20 min", portions: 4,
    steps: "Mix mince with spices, shape into koftas on skewers.\nGrill 10-12 min, turning occasionally.\nServe in flatbreads with cucumber, yoghurt and mint." },
  { id: "custom-94", name: "Vegetable and chickpea salad bowl", protein: "other",
    ingredients: [{ name: "Chickpeas", amount: "2", unit: "cup" }, { name: "Cucumber", amount: "1", unit: "whole" }, { name: "Tomato", amount: "2", unit: "whole" }, { name: "Feta", amount: "100", unit: "g" }, { name: "Olive oil", amount: "2", unit: "tbsp" }],
    spices: ["Oregano", "Black pepper", "Salt"], method: "hob", temp: "", time: "15 min", portions: 4,
    steps: "Warm chickpeas gently or use at room temperature.\nChop cucumber and tomato, combine with chickpeas.\nTop with crumbled feta and a drizzle of olive oil." },
  { id: "custom-95", name: "Chicken and vegetable skewers with rice", protein: "chicken",
    ingredients: [{ name: "Chicken breast", amount: "500", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Courgette", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Lemon", amount: "1", unit: "whole" }],
    spices: ["Paprika", "Garlic powder", "Salt"], method: "bbq", temp: "", time: "20 min", portions: 4,
    steps: "Thread chicken and vegetables onto skewers, season.\nGrill/BBQ 15 min, turning occasionally.\nServe over rice with a squeeze of lemon." },
  { id: "custom-96", name: "Beef and potato curry", protein: "beef",
    ingredients: [{ name: "Diced beef", amount: "600", unit: "g" }, { name: "Potatoes", amount: "3", unit: "whole" }, { name: "Tinned tomatoes", amount: "400", unit: "g" }, { name: "Onion", amount: "1", unit: "whole" }, { name: "Rice", amount: "300", unit: "g" }],
    spices: ["Garam masala", "Turmeric", "Cumin"], method: "slow-cooker", temp: "Low", time: "6 hr", portions: 4,
    steps: "Add all ingredients except rice to the slow cooker.\nCook on low 6 hours until beef is tender.\nServe over rice." },
  { id: "custom-97", name: "Vegetable and halloumi kebabs", protein: "other",
    ingredients: [{ name: "Halloumi", amount: "250", unit: "g" }, { name: "Peppers", amount: "1", unit: "whole" }, { name: "Red onion", amount: "1", unit: "whole" }, { name: "Courgette", amount: "1", unit: "whole" }, { name: "Couscous", amount: "200", unit: "g" }],
    spices: ["Smoked paprika", "Cumin"], method: "bbq", temp: "", time: "20 min", portions: 4,
    steps: "Thread halloumi and vegetables onto skewers.\nGrill/BBQ 12-15 min, turning occasionally.\nServe with couscous." },
  { id: "custom-98", name: "Chicken and rice one-pot", protein: "chicken",
    ingredients: [{ name: "Chicken thighs", amount: "600", unit: "g" }, { name: "Rice", amount: "300", unit: "g" }, { name: "Peas", amount: "100", unit: "g" }, { name: "Chicken stock", amount: "600", unit: "ml" }, { name: "Onion", amount: "1", unit: "whole" }],
    spices: ["Turmeric", "Salt", "Black pepper"], method: "hob", temp: "", time: "35 min", portions: 4,
    steps: "Brown chicken and onion.\nAdd rice and stock, simmer covered 20 min.\nStir in peas for the last 5 min." },
  { id: "custom-99", name: "Beef and vegetable fried noodles", protein: "beef",
    ingredients: [{ name: "Beef strips", amount: "400", unit: "g" }, { name: "Egg noodles", amount: "250", unit: "g" }, { name: "Cabbage", amount: "150", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Soy sauce", amount: "3", unit: "tbsp" }],
    spices: ["Ground ginger", "Chinese five spice"], method: "hob", temp: "", time: "20 min", portions: 4,
    steps: "Fry beef until browned, set aside.\nStir fry cabbage and carrots.\nAdd noodles, beef and soy sauce, toss together." },
  { id: "custom-100", name: "Vegetable and lentil soup", protein: "other",
    ingredients: [{ name: "Red lentils", amount: "200", unit: "g" }, { name: "Carrots", amount: "2", unit: "whole" }, { name: "Celery", amount: "2", unit: "whole" }, { name: "Vegetable stock", amount: "1", unit: "l" }, { name: "Onion", amount: "1", unit: "whole" }],
    spices: ["Cumin", "Turmeric", "Salt"], method: "slow-cooker", temp: "Low", time: "5 hr", portions: 4,
    steps: "Add all ingredients to the slow cooker.\nCook on low 5 hours.\nBlend partially or fully for a smoother texture if preferred." },
];
